# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "colon_new"
  entity: 'jucheon'
  name: ${name}
  save_dir: "."
  offline: False # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
#  tags: ['multirun','test']
  tags: null
  reinit: True
#  settings: wandb.Settings(start_method="thread")